version: '3.8'

services:
    main:
        container_name: Serve
        build:
            context: .
            dockerfile: DockerfileDev
        command: 'php artisan serve --host=0.0.0.0'
        ports:
            - 8000:8000
