openapi: 3.0.3
info:
  title: 'The big bang theory API.'
  description: ''
  version: 1.0.0
servers:
  -
    url: 'http://localhost'
paths:
  /api/user:
    get:
      summary: ''
      operationId: getApiUser
      description: ''
      parameters: []
      responses:
        401:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  message: Unauthenticated.
                properties:
                  message:
                    type: string
                    example: Unauthenticated.
      tags:
        - Endpoints
      security: []
  /api/characters/leonard:
    get:
      summary: ''
      operationId: getApiCharactersLeonard
      description: ''
      parameters: []
      responses:
        200:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  message: 'Hello, here is Leonard!'
                properties:
                  message:
                    type: string
                    example: 'Hello, here is Leonard!'
      tags:
        - 'The Big Bang Theory characters'
      security: []
tags:
  -
    name: Endpoints
    description: ''
  -
    name: 'The Big Bang Theory characters'
    description: "\nAPIs for managing users"
components:
  securitySchemes:
    default:
      type: http
      scheme: bearer
      description: ''
security:
  -
    default: []
